### ISSUE TITLE
Add number of critic review and user ratings

### ISSUE THREAD

**Issue by wwtubs** [henrylin03/video-games#19]
It is interesting, for my own purposes, to add the number of critic reviews and the number of user ratings for each game. I would be happy to open a PR for this if this repo is still active.

**Comment by henrylin03** [comment]
Please feel free to open a PR!

**Comment by wwtubs** [comment]
I looked into this and saw that it would be a lot more involved than I had anticipated. I was unable to find a page which easily listed the number of critic reviews and user ratings. On top of that, scraping is a ToS violation and I cannot use it for academic research because of that :(.

**Comment by henrylin03** [comment]
Hey Connor - thanks for looking into this. It seems that you'd have to open each individual game and pull the count of ratings from there (example game - [link](https://www.metacritic.com/game/ds/grand-theft-auto-chinatown-wars))
![image](https://github.com/henrylin03/video-games/assets/83106787/3666e466-6458-4507-9583-a01a912d3c55)

I've tried to avoid having to click through each game in something like `selenium` and then extract information from there, rather than getting as much metadata as possible for list of games.

Thanks again for contributing

**Comment by wwtubs** [comment]
Yeah, that makes a lot of sense. I have opted for using the OpenCritic API for this kind of information. If I had more time available for this research I would have loved to contribute.
